### ISSUE TITLE
Google Friendly Urls

### ISSUE THREAD

**Issue by barisakpunar** [yagopv/BgEngine#3]
Very good project. Do you consider adding Google Friendly Urls. It'll be very good feature.

Instead of "http://www.yagoperez.com/Post/GetPostByCode/el_mecanismo_de_binding_en_ASP_MVC"
this
"http://www.yagoperez.com/ASP_MVC/el_mecanismo_de_binding_en_ASP_MVC"

**Comment by yagopv** [comment]
Hi!!

Thanks for spending your time taking a look to my project :)

About the SEO friendly URLs ... i already tried to create the URLs in that way. Actually, BgEngine urls are following de MVC route pattern and avoiding parameters usage ...

{controller}/{action}/{id}

... in most of cases like in 

{Post}/{GetPostByCode}/{The post code}
{Post}/{GetPostByTag}/{The tag}
{Post}/{GetPostByDate}/{year}/{month}

Perhaps the literals are not clear enough and i could allow using spaces or hyphens instead underscores in urls ...

Date: Sun, 13 Jan 2013 04:13:28 -0800

**Comment by barisakpunar** [comment]
Thank you for your reply.

In fact I mean like this "http://www.yagoperez.com/{SubjectCategoryName}/{PostTitle}

Maybe it is not easy or make more complex the url structure. But this will be SEO friendly and also human friendly.

Thanks.

**Comment by yagopv** [comment]
Hi,

I think it would not be very complicated changing urls to that format by updating the app route table and adding a new action for retrieving single posts with the parameters you commented ({category} or {tag} / {title})

I´ll take a look to that ... perhaps i can cook it ... Thanks for the tip!!

Date: Mon, 14 Jan 2013 05:37:11 -0800
